spring:
  mail:
    host: smtp.163.com
    username: zyp0759
    password: 13531145222qq
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/jobhunter?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/comweb/
#  freemarker:
#    charset: UTF-8
#    template-loader-path: classpath:/jobweb/templates/
#    suffix: .html
#    # 关闭缓存
#    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8080


#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#server:
#  port: 80
#management:
#  ssl:
#    key-store: classpath:/keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
#    protocol: TLS
#    key-password: 123456
#    key-store-password: 123456
#    client-auth: want

#server:
#  port: 8080
#  max-http-header-size: 10000
#  connection-timeout: 20000
#  tomcat:
#    max-threads: 150